#include layouts\column.ahk
#include layouts\floating.ahk
#include layouts\fullscreen.ahk
#include layouts\row.ahk
#include layouts\spiral.ahk
#include layouts\tall.ahk
#include layouts\threecolumn.ahk
#include layouts\twopane.ahk
#include layouts\wide.ahk
