name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - features/ci-wip

env:
  AHK_V2_URL: https://github.com/AutoHotkey/AutoHotkey/releases/download/v2.0.11/AutoHotkey_2.0.11.zip
  AHK2EXE_URL: https://github.com/AutoHotkey/Ahk2Exe/releases/download/Ahk2Exe1.1.37.02a0/Ahk2Exe1.1.37.02a0.zip

jobs:
  prepare:
    runs-on: windows-2019
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and extract AutoHotkey
      run: |
        irm -OutFile autohotkey.zip $env:AHK_V2_URL
        unzip autohotkey.zip -d autohotkey
        irm -OutFile ahk2exe.zip $env:AHK2EXE_URL
        unzip ahk2exe.zip -d autohotkey\Compiler

  build:
    runs-on: windows-2019
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Embed script with Ahk2Exe
      run: .\scripts\embed.ps1

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: mwm
        path: |
          build/mwm.exe
          build/mwm.ahk
